version: '3'
services:
  SQLServer:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup      
    ports:
      - '1500:1433'
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
    networks:
      - database-net

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:

networks: 
    database-net:
      driver: bridge      